version: "3.6"

services:
 luanti:
  image: ghcr.io/luanti-org/luanti:5.14.0
  entrypoint: ["luantiserver", "--config", "/minetest.conf"]
  user: root
  ports:
    - 30000:30000/udp
  volumes:
    - "./worldmods:/root/.minetest/worlds/world/worldmods/"
    - "./minetest_game:/root/.minetest/games/minetest_game"
    - "./export:/root/.minetest/worlds/world/mtwebview/"
    - "world_data:/root/.minetest/worlds/world"
    - "./worldmods/export_mod/test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./worldmods/export_mod/test/minetest.conf:/minetest.conf"
    - "./worldmods/export_mod/testschematic.we:/root/.minetest/worlds/world/schems/testschematic.we"

 npm:
  image: node:24.9.0
  volumes:
   - "./:/app"
  working_dir: /app
  command: ["sh", "-c", "npm ci"]

 watch:
  image: node:24.9.0
  volumes:
   - "./:/app"
  working_dir: /app
  command: ["sh", "-c", "npm ci && npm run watch"]

 nginx:
  image: nginx:1.29.1
  restart: always
  ports:
   - 8080:8080
  volumes:
   - "./nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./:/html"

volumes:
  world_data: {}
